services:
  - type: web
    name: tross-linkedin-profile-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /health
